### PR TITLE
Do not store compiled bytecode

### PR DESCRIPTION
**Pull request by ccorbacho**
Compiled bytecode files (*.pyc, *.pyo and __pycache__) should not be committed in Git (even for testing) - these are not supposed to be packaged up, and are Python version specific.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @ccorbacho,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsPython is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by ccorbacho** [comment]
@jessp01 You may want to ignore kaltura-hooks here and merge this one anyway, as this repo really should have a proper .gitignore and not be committing bytecode.

**Comment by jessp01** [comment]
Hi @ccorbacho,
Yes, this particular pull is an exception to the rule:)
Please reopen and I will merge.

**Comment by jessp01** [comment]
nm, reopened it myself, thanks:)

**Pull request merged**
